### ISSUE TITLE
Can't load Settings file

### ISSUE THREAD

**Issue by cosmicdreams** [ergonlogic/aegir-up#1]
When trying to get aegir installed using aegir-up to
aegir-up/Vagrantfile:2:in `require': cannot load such file -- settings (LoadError)

Which seems to be related to not being able to load the settings file at all.  I was able to push past this issue by pasting the contents of the settings file to the top of the VagrantFile. 

Windows 7 
Vagrant 1.5.2
Ruby 2.0.0p481

**Comment by Genghoidal** [comment]
Late answer but this requires reference such as   ./settings.rb

**Comment by ergonlogic** [comment]
Sorry, but this project is long-abandoned, as illustrated by the last commit being 4+ years ago. However, I invite you to check out its successor: [Valkyrie](https://github.com/GetValkyrie/valkyrie). Altervatively, for just a straight-up install of Aegir in Vagrant, check out https://github.com/ergonlogic/ansible-role-aegir, which ships with a Vagrantfile. I'm actively working on the latter, and should be pushing some new code today to install Aegir via .debs.
